create table enrollment (
        lecture_registration_id bigint generated by default as identity,
        lecture_id varchar(255),
        registration_status varchar(255) check (registration_status in ('REGISTERING','REGISTERED','FAILED')),
        user_id varchar(255),
        primary key (lecture_registration_id)
);
create table lecture (
        current_enrollment integer,
        max_enrollment integer,
        lecture_date timestamp(6) with time zone,
        lecture_id varchar(255) not null,
        primary key (lecture_id)
);

INSERT INTO lecture(lecture_id, current_enrollment, lecture_date, max_enrollment)
VALUES ('1', 0, '2024-03-25 13:46:07.802371+09', 1);
